document.write('<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">');
document.write('<html xmlns="http://www.w3.org/1999/xhtml">');
document.write('<head>');
document.write('<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />');
document.write('</head>');
document.write('<body style="height:2000px;">');
document.write('<script type="text/javascript">function closeDiv(innerCall){if(document.getElementById("PcPoPmarket_9229")==null)return;document.getElementById("PcPoPmarket_9229").style.display = "none";}');
document.write('</script>');
document.write('<div style="z-index: 1000; right: 0px; bottom: 0px; overflow-x: hidden; overflow-y: hidden; position: fixed; width: 300px; height: 250px; " id="PcPoPmarket_9229">');
document.write('<div style="z-index:1000; POSITION: absolute; right:0; height:30px; overflow:hidden;">');
document.write('<span style="width:18px; height:18px; cursor:pointer; float:right; margin-left:1px; margin-top:12px; display:inline; background:url(/assets/img/buttons.png) no-repeat; hover{background-position:-39px -20px};margin-right:10px; width:15px; background-position:-39px 0;" onclick="closeDiv()"></span>');
document.write('</span></div>');
document.write('<iframe id="popFrame" scrolling="no" frameborder="0" width="300" allowtransparency="true" height="250" src="/newad/exchange/ad_9229_0.html" target="_blank">-</iframe>');
document.write('</div>');
document.write('</body>');
document.write('</html>');
